apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: device-system-service
spec:
  selector:
    app: device-system
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: device-system
  labels:
    app: device-system
spec:
  replicas: 1
  template:
    metadata:
      name: device-system
      labels:
        app: device-system
    spec:
      containers:
        - name: device-system
          image: device-manage-system:dev
          resources:
            limits:
              memory: "350Mi"
            requests:
              memory: "350Mi"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ACTIVE_ENV
              value: dev
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /etc/timezone
              name: timezone
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          hostPath:
            path: /etc/timezone
      restartPolicy: Always
  selector:
    matchLabels:
      app: device-system

