server:
  port: 8081
  servlet:
    session:
      timeout: 600
spring:
  # mysql Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device_manage_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: root
    username: root


logging:
  level:
    org.cust.devicemanagesystem.mapper: debug
